<script lang="ts">
  const projects = [
    { mediaClass: 'lg:col-span-3 flex justify-center', title: 'Mana Counter', site: 'https://manacounter.bhm.gg', repo: 'https://github.com/BlackHat-Magic/ManaCounter', preview: true, text: ['A quick web app that tracks mana in Magic: the Gathering for those thirty-minute turns in which your mana pool gets flooded.', 'This was built in about an hour <s>because apparently I have to do everything myself</s> because there was a distinct lack of results on Google for mana counters that didn\'t demand you download an app.'] },
    { mediaClass: 'lg:col-span-3 flex-col items-center justify-center', imageClass: 'min-w-[50%] mx-auto', captionClass: 'text-xs leading-relaxed text-foreground mb-8 text-center', title: 'Palladia Engine', repo: 'https://github.com/BlackHat-Magic/Palladia-Engine', image: '/images/palladia.gif', alt: 'A gif depicting a spinning torus', caption: "Right now the engine doesn't do much, so here's a spinning donut.", text: ['The Palladia Engine is a simple, ECS-based game engine written in C using the SDL GPU API. Currently, it only targets a Vulkan backend, but the goal is to at least also support WebGPU. Most of the code written so far is loosely based on the <a href="https://learnopengl.com/" target="_blank" class="hover:underline">Learn OpenGL tutorials</a>, at least as far as they can be for using an entirely different graphics API.', 'The project stemmed from a desire to learn graphics programming and the fact that, in game programming, I often find myself knowing exactly what I want the code to look like, but unsure of how to tell the game engine to do what I want. So I figured that several hundred hours of trial and error should save me thirty or so minutes of reading the Godot documentation.', 'I intend to come back to this, but as of writing this, my university capstone project is taking up a lot of my time.'] },
    { mediaClass: 'lg:col-span-3', captionClass: 'text-xs leading-relaxed text-foreground mb-8', title: 'Piru', repo: 'https://github.com/BlackHat-Magic/Piru', image: '/images/piru.jpg', alt: "I couldn't think of a good image for this one, so here's Piru the Volatile from Magic: The Gathering.", caption: "I couldn't think of a good image for this one, so here's Piru the Volatile from Magic: The Gathering.", text: ['The way this project came about is kind of funny. When I was doing my internship at NSHC in the summer of 2025, I was tasked with reading and creating a presentation on the <a href="https://bellard.org/tcc/" target="_blank" class="hover:underline">Tiny C compiler</a> by Fabrice Bellard. Perhaps because of the language barrier, I had misinterpreted this as being to <em>write</em> a very simple compiler. I had gotten as far as writing a lexer and parser using a <a href="https://kuterdinel.com/writing-a-very-simple-jit-compiler-in-about-1000-lines-of-c.html" target="_blank" class="hover:underline">tutorial by Kuter Daniel</a> before the misunderstanding had been cleared up.', 'The compiler targets the RV64I instruction set for portability. The idea is that the compiled code will run in a virtual machine that executes the RISC-V instructions so that only the VM, not the runtime code, has to be recompiled for new platforms. This virtual machine is, of course, part of the project. As a part of preparing to write this project, I followed a <a href="https://www.jmeiners.com/lc3-vm/" target="_blank" class="hover:underline">tutorial by Justin Meiners and Ryan Pendleton</a> detailing how to write a simple LC-3 virtual machine, and the RV64I VM would be based on that.', 'I intend to come back to this, but as of writing this, my university capstone project is taking up a lot of my time.'] },
    { mediaClass: 'lg:col-span-3 flex justify-center', title: 'Lyci.link', site: 'https://lyciberi.bhm.gg', repo: 'https://github.com/BlackHat-Magic/Kiko-gg', preview: true, text: ['This site serves as a landing page for a friend\'s social media presence—similar to <a href="https://carrd.co" target="_blank" rel="noopener noreferrer" class="hover:underline">Carrd</a> or <a href="https://linktr.ee" target="_blank" rel="noopener noreferrer" class="hover:underline">Linktree</a>.', 'It was recently refactored to use Tailwind instead of plain CSS.'] },
    { mediaClass: 'lg:col-span-3 flex justify-center', title: 'Kiko.gg', site: 'https://kiko.gg', repo: 'https://github.com/BlackHat-Magic/Kiko-gg', preview: true, text: ['This site <em>also</em> serves as a landing page for a friend\'s social media presence—similar to <a href="https://carrd.co" target="_blank" rel="noopener noreferrer" class="hover:underline">Carrd</a> or <a href="https://linktr.ee" target="_blank" rel="noopener noreferrer" class="hover:underline">Linktree</a>. This one came first, but the projects are listed in reverse chronological order.', 'It was recently refactored to use Tailwind instead of plain CSS.'] },
    { mediaClass: 'lg:col-span-3 flex justify-center', title: 'Three.js Test', site: 'https://three.lukeh.xyz', repo: 'https://github.com/BlackHat-Magic/ThreeJS-Test', preview: true, text: ['I built this site as a means of familiarizing myself with <a href="https://threejs.dev" target="_blank" rel="noopener noreferrer" class="hover:underline">Three.js</a>. The text was generated by GPT-3.5 turbo.', "It might not render correctly in the small preview window depending on your screen's resolution, so open it in a new tab to view it properly."] },
    { mediaClass: 'lg:col-span-3 flex justify-center', wrapperClass: 'max-w-7xl', imageClass: 'h-40 w-40 rounded-full object-cover shadow-lg ring-2 ring-gray-200', title: 'Lukeh.xyz', site: 'https://lukeh.xyz', repo: 'https://github.com/BlackHat-Magic/Kiko-gg', image: '/images/me lon pc.webp', alt: 'A photo of Luke Henderson', text: ['This site serves as my developer portfolio and is built with Alpine, Tailwind, and Cloudflare Pages.', 'Alpine was chosen for similar reasons; this site isn\'t seriously limited by the "HTML with interaction on top" approach that using something like vanilla JavaScript or jQuery has. I find Alpine to be more ergonomic than those without inflating the client bundle to multiple megabytes in the way that React would likely do.', 'I really dragged my feet on adding Tailwind, but the ability to use existing component libraries was something I couldn\'t ignore any longer.'] },
    { mediaClass: 'lg:col-span-3 flex justify-center', wrapperClass: 'max-w-7xl mb-16', title: 'bhm.gg', site: 'https://bhm.gg', repo: 'https://github.com/BlackHat-Magic/BHM-gg', preview: true, text: ['This site serves as a landing page for <em>my own</em> social media presence—similar to <a href="https://carrd.co" target="_blank" rel="noopener noreferrer" class="hover:underline">Carrd</a> or <a href="https://linktr.ee" target="_blank" rel="noopener noreferrer" class="hover:underline">Linktree</a>. This one was used as reference for the other two. It also usually gets any updates that I might implement before the other two.', 'It was recently refactored to use Tailwind instead of plain CSS.'] }
  ];
</script>

<main class="mx-auto flex min-h-screen flex-col items-center justify-center px-6 text-left">
  <div class="flex items-center justify-center mx-auto text-center max-w-7xl mb-16 mt-16"><h1 class="text-2xl font-black leading-tight">All Projects</h1></div>
  {#each projects as project}
    <div class={project.wrapperClass || 'max-w-7xl mb-16'}><div class="grid gap-6 lg:grid-cols-5 items-start">
      <div class={project.mediaClass}>
        {#if project.preview}
          <div class="w-full aspect-[3/4] max-w-[720px] rounded-lg overflow-hidden"><iframe src={project.site} title={`${project.title} Preview`} class="h-full w-full" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
        {:else if project.image}
          <img src={project.image} alt={project.alt} class={project.imageClass} />{#if project.caption}<p class={project.captionClass}>{project.caption}</p>{/if}
        {/if}
      </div>
      <div class="lg:col-span-2"><h2 class="text-xl font-black leading-tight">{#if project.site}<a href={project.site} target="_blank" rel="noopener noreferrer" class="hover:underline">{project.title}</a>{:else}{project.title}{/if}</h2><div class="mb-4"><a class="text-xs leading-tight text-blue-600 hover:underline" href={project.repo} target="_blank" rel="noopener noreferrer">Source Code</a></div>{#each project.text as paragraph}<p class="prose max-w-prose text-lg leading-relaxed text-foreground sm:text-xl mb-8">{@html paragraph}</p>{/each}</div>
    </div></div>
  {/each}
</main>
